/*
 	Name:
	Course:
	Date Created:
	Last Modification Date:

	Summary:
		coverage1.c is a report of the coverage generated by gcov for cominion.c
	
	Dominion.c
	1. Lines executed:		36.81%
	2. Branches taken:		47.62%
	3. At least once:		36.43%
	4. Calls taken:			20.83%
	5. Overview:
		The low score is to be expected. Assignment 03 was to pick 4 functions from 
		dominion.c, along with 4 card implementations. Dominion features dozens of 
		cards and therefore functions with which one could test. Moreover, there are
		many different functions throughout dominion.c In order to achieve 100% 
		coverage, a very, very robust test suite will be needed.

		Each test also featured a default test group which compared how player 2 
		fares, the overall state of score cards and coins.

	1. unittest1.c
		Lines executed:81.82% of 44
		Branches executed:100.00% of 12
		Taken at least once:66.67% of 12
		Calls executed:64.71% of 17

		Unit test 1's test of shuffle showed 100% coverage of branches. I think low 
		rates for calls and taken are due to repesenting failing cases; tests were
		designed using if-else, which would produce these holes.

	2. unittest2.c
		Lines executed:94.74% of 57
		Branches executed:100.00% of 6
		Taken at least once:66.67% of 6
		Calls executed:70.00% of 10
		
		Unit test 2's test of getCost slightly higher calls executed. Lines not being
		executed, as well as 67% taken rating may be due to the if-else structure
		employed.

	3. unittest3.c
		Lines executed:86.99% of 292
		Branches executed:100.00% of 74
		Taken at least once:67.57% of 74
		Calls executed:76.35% of 203

		Unit test 3 was a test of the scoreFore() function. It's results are skewed. I 
		this this is due to the gardens card, which I have made note in bugs1.c.
		The card's function is lacking in some ways, leading it to not always execute.

	4. unittest4.c
		Lines executed:88.73% of 71
		Branches executed:100.00% of 10
		Taken at least once:60.00% of 10
		Calls executed:78.38% of 37

		Unit test 4 was of updateCoins. The lack of calls may be due to the if-else
		error handling method.

	5. cardtest1.c
		Lines executed:96.88% of 32
		Branches executed:100.00% of 6
		Taken at least once:50.00% of 6
		Calls executed:92.31% of 13

		Card test 1 was that of smithy. It's amazingly low path coverage is due to the
		bugs introduced into smithy during refactor1. Part of the function will simply
		never execute properly, that is the discardCard().

	6. cardtest2.c
		Lines executed:89.19% of 37
		Branches executed:100.00% of 8
		Taken at least once:50.00% of 8
		Calls executed:71.43% of 14

		Card test 2 is the test for Great_Hall. While featuing high line and branch
		coverage, the path coverage is minimal. This should warrant further testing in
		the future.

	7. cardtest3.c
		Lines executed:91.67% of 36
		Branches executed:100.00% of 6
		Taken at least once:50.00% of 6
		Calls executed:76.92% of 13

		Card test 3 tests the council room. Unfortunately, it has a path coverage of 
		50%. This is in part to the limited methods of input possible for Great_Hall.

	8. cardtest4.c
		Lines executed:92.50% of 40
		Branches executed:100.00% of 12
		Taken at least once:66.67% of 12
		Calls executed:76.92% of 13

		The Adventurer card is card test 4. Here also features low path coverage.

	9. Reflection
		Nearly all test featured path coverage of 65-75%. This is fairly low and definitely
		reflects poor coverage in that regard. However, there is high line covered, with the
		loweres being 86%. There is also 100% branch coverage, suggesting the tests worked
		in exploring the functions properly. 

		In the future, it would be important to introduce more edge case tests to prove
		not only that a function is working correctly when it produces good output, but
		also flat out wrong output. For example, no test examines when negative values
		are erroneously passed into the functions. 





*/
