Tested with refactored dominion.c file
(Note: The %coverages that I reported for each individual testcase is for that individual testcase only.)

Unittest1.c - Testing discardCard function
The discardCard function works by removing a card from the player's hand and either discarding it or trashing it. If the card is discarded, as set by a trashFlag of 0, then it is added to the playedCard pile. If the card is trashed, as set by a trashFlag of 0, then it is just removed and not recorded in any other array. The card is then removed from the current player's hand array properly, depending on its location. Since the discardCard function has an if statement and an if/else if/else statement, branch coverage would be good for this. The gcov analysis showed that unittest1.c executes 2.13% of 564 lines in dominion.c. Evalation of dominion.c.gcov shows that unittest1.c executes the function 4 times, and all lines except for the else if body in the second if conditional executes. This is interesting because this body may never execute as if a player only has one card in their hand, then it is at position 0. Position 0 is 1 less than the total, which means that no matter what, the body of the if statement will execute. Because this body may never be executed, it may not be necessary in the function. Overall, unittest1.c has pretty good branch coverage as each possible path is reached.

Unittest2.c - Testing shuffle function
Unittest2.c tests the shuffle function in dominion.c. The shuffle function essentially takes the current player's deck, sorts it, and then reorders the deck by using a random number function. If the player's deck is empty, then the function returns with -1. The function seems to have two pain logic paths - one for non-empty decks and one for empty decks so I chose to implement branch coverage in my testing. In Unittest2.c, I called the function 3 times with 3 different sets of input, 1 of which had a deck of size 0. In doing so, this ensured statement and branch coverage, as each node and edge in the function will be passed through at least once. The gcov results showed that unittest2.c executes 3.90% of 564 lines in dominion.c. Closer evaluation of dominion.c.gcov shows that all the lines in the compare function are run. In the shuffle function, 3 of the data initialization lines appear to have not been executed, which is a bit confusing because those are mandatory steps. However, the rest of the lines, which means each path, have been executed so this testcase has good branch coverage. The if statement that checks if a deck is 0 is run 3 times and the function only returns -1 once, which is expected. The lines in the while and for loops, which execute if the deck is greater than 0, were executed between 25-112 times. The function returns 0 twice, which is expected as out of the 3 total runs, the deck was greater than 0 twice.

Unittest3.c - Testing fullDeckCount function
Unittest3.c tests the fullDeckCount function, which essentially takes in a card in question and counts the total number of times that the card is found in the current player's hand, deck, and discard pile. The fullDeckCount function is pretty simple - there is only one direct path through the function, which primarily consists of 3 for loops. fullDeckCount has no conditional statements and therefore to get good testing coverage, I just needed to use statement coverage. To make sure all the for loops are executed though, my inputs for the deck, hand, and discount counts and arrays needed to be greater than 1. Running gcov showed that this testcase only executes 1.60% of 564 lines in the dominion.c file. Analysis of the dominion.c.gcov file shows that all the lines are executed, except for the first intialization statement (int i=0), which I am sure was executed in order for the function to be successful. Each of the lines associated with the for loops are executed between 60-156 times, and the function returns 12 times, as the function was run 12 different times by unittest3.c. My testcase overall had good statement coverage.

Unittest4.c - Testing updateCoins function
The updateCoins function calculates the number of treasure cards in the current player's hand. updateCoins has a for loop which encompasses an if/else if/else if statement. To make sure I tested each of the conditional scenarios through the function, branch coverage was needed in this case. Since there is only one if/else if/else if statement, the inputs needed to be diverse enough to pass through if and each of the else if statements. To do this, I made sure my inputs included copper, silver, and gold treasure cards. In addition, the handCount input needed to be greater than 0 in order to enter the for loop. The gcov analysis showed that this unit test executes 1.95% of 564 lines in the dominion.c file. As seen in unittest3.c analysis, int i=0 execution was not shown in the dominion.c.gcov file; all the other lines were executed. The lines of code in the if/else if/else statements were run between 4 to 19 times; the if statement is run the most whereas the last else if statement is run the least. This makes sense, as the code runs top-down, and serves as a reminder that my inputs should be as diverse as possible so later else if or else statements will be run. The rest of the code is run 4 times, as unittest4.c called the updateCoins function 4 times. My testcase had decent branch coverage, but could be improved with more diversity in the inputs.

Cardtest1.c - Testing adventurer card
The adventurer card makes the current player draw cards until he/she has 2 treasure cards. The rest of the cards are then discarded. The bugs I introduced modified how the function works though. The adventurer code is a bit complex, it has 2 while loops, an if statement, an if/else statement, and calls 2 functions. As there are many different paths, or edges, in adventurer, I used branch coverage to cover each edge at least once. Cardtest1.c called this function 4 times with 4 different sets of inputs. The first while loop houses an if statement and an if/else statement. To enter the first if statement, 2 of my inputs had a deck count of 0 so that the shuffle function would be called. The cardDrawn function is then called and the second if/else statement evaluates the card that is drawn. To make sure both the if and else are evaluated, I made sure the decks and discard piles (if the deck is 0) had half adventure and half treasure cards to make it more probable that both will be run. The final while loop is run afterwards, and its chances of running multiple times is also contingent on preparing the decks and discard piles with 50/50 adventure and treasure cards. The gcov analysis showed that the cardtest1.c executes 12.77% of the 564 lines in the dominion.c file. All the code within both while loops, including the if and if/else statements, were executed almost an equal number of times. In the if/else statement, the first if statement is evaluated 33 times and the contents of the else statement are run 21 times. In addition, the drawCard, shuffle, compare, and whoseTurn functions are executed several times and most of their lines are executed, but not all. Some of the intialization code and the first if statement in cardEffect are executed as well. Cardtest1.c could be improved by adding more tests and different inputs to make sure all the possible code in the different functions are executed at least once, but it overall has good coverage for the adventurer function.

Cardtest2.c - Testing smithy card
The smithy card has the current player draw three cards and discard one. The code calls the drawCard function 3 times and then the discardCard function afterwards. Cardtest2.c runs through smithy 4 times; dominion.c.gcov shows that the drawCard function is called a total of 12 times within a for loop and discardCard is called 4 times total. Since the smithy code alone does not have any conditionals, using branch coverage to make sure the drawCard and discardCard functions were well tested was important. The gcov analysis shows that cardtest2.c covers 12.77% of 564 lines in dominion.c. The dominion.c.gcov file shows that every line (aside from some intiailization lines whose analysis may not have been recorded) in drawCard was executed between 2 - 46 times (except for the debug statements). All the loops, conditional statements, and qsort in the shuffle function are executed between 2-339 times. In addition, all the lines in the compare function were executed between 16-104 times. One issue that is apparent is the discardCount function, in which not all of the lines are executed. Most of the lines are executed 4 times but in the if/else if/else statement, only the contents of else were executed. As mentioned in the discardCard function analysis, the else if body may never be possible to execute, but the if body can. This identifies an area of improvement for my testcase, Cardtest2.c; I need to add a handPos input that is one less than the handCount so that the body of the if statement will run. In addition, the last if statement in drawCard is not executed, which is indicative that I did not test what would happen if both deck and discard were empty. If these areas is fixed, then my testcase would achieve branch coverage.

Cardtest3.c - Testing great hall card
The great hall card has the current player draw a card and discard a card. The numActions also increases by 1. Similar to the smithy card, the great hall code calls drawCard and discardCard, both of which have conditionals and loops. Therefore, it is important to have branch coverage in this case. The gcov analysis showed that cardtest3.c covers 12.41% of 564 lines in dominion.c. From dominion.c.gcov it can be seen that all the code in the compare function are executed between 27-141 times, which is pretty good coverage. All the code in the shuffle function is executed between 2-467 times, aside from some intiailization statements (which may not have been recorded) and the if statement that returns if the deck is empty. This is a line of code that is hard to test from great hall because the function that calls it, drawCard, fills up the deck if it is empty. The only way to test it would be to have the deck and discard count be 0, which is an input I did not include and should add to make my testing more complete. All lines in drawCard, aside from the debug statements, the last if statement, and one intiailization statement (that most definitely was executed), are run between 2-56 times. The last if statement in drawCard would run if I set the deck and discard to 0; this reaffirms the idea of doing so to improve my testcase. Next, the discardCard function sees most of its lines run except for the body of the else if in the if/else if/else statements - however as discussed prior, this may never run. Overall, minor improvements to cardtest3.c will help it achieve branch coverage.

Cardtest4.c - Testing council room card
The council room card has the current player draw 4 cards and discard one card. The numBuys is increased by one and each other player draws 1 card. The code calls the drawCard function 4 times in the first for loop, up to 3 more times in a scond for loop, and then calls the discardCard function. Branch coverage is needed to evaluae the council room code and the code within the function it calls since those functions have several conditional statements and loops. The gcov analysis shows that this testcase execued 12.77% of 548 lines in dominion.c. Dominion.c.gcov shows that all the lines in the compare function are evaluated between 64-336 times, which is pretty good coverage. The code in whoseTurn function were all run as well. All the code in the shuffle function are executed between 6-963 times, except for the first if statement (and minus the initiliaztion statements). This should be rectified by testing inputs of 0 for the deck and discard count. All the code in drawCard is executed, except for the last if statement and the intialization statements that I'm sure were run. This is a definite area of improvement I can make. In addition, the body of the if in the second if statement was not executed in the discardCount. This is an issue that I have seen and discussed before; thus being more aware of testing the right input to achieve branch coverage will make my test case stronger.

All together:
When all the unit tests are run together, they produce a total coverage of 21.81% out of 564 lines.
Several functions, such as compare, shuffle, fullDeckCount, whoseTurn, drawCard, discardCard, and updateCoins see pretty good coverage overall since they are called by one or more unit tests. My test suite does need improvement; there are a lot of reoccuring issues that I have discussed and faced with different test cases and it all comes down to testing more critical inputs in order to achieve better coverage.


































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
