Smithy Card: When a player draws a smithy card, they automaticaly draw 3 cards from their deck. This is done in a for loop that iterates 3 times and calls the drawCard function 3 times. A card is then discarded from the player's hand with the discardCard function.

Adventurer Card: If the adventurer action card is played, several things happen as defined in the cardEffect function in
dominion.c. The current player keeps drawing cards from the deck, in a while loop, until 2 treasure cards have been drawn.
Each iteration of the while loop checks the value of the drawntreasure variable, initialized to 0, which is incremented when a treasure
card is drawn. Thus in each iteration, a card is drawn. During each draw, if the deck is empty, then the deck is shuffled with the shuffle function.
The drawCard function is called to draw a card from the deck, and the cardDrawn local variable is set to the most recently drawn card, which is essentially the last value in the state->hand array for the current player. If the drawn card is a copper, silver, or gold, then the drawntreasurer variable is increased. Otherwise, the card is added to the temphand array and the number of cards the current player has decreases by 1 (state->handCount array). The drawntreasurer variable does not change in this case. After drawntreasuer >= 2, meaning 2 treasure cards have been drawn, the program moves to another while loop to discard the cards in the temphand array from the current player's hand.
As long as the temphand array is not empty, the while loop iterates through the temphand array and discards each card represented in the
temphand array from the current player's hand by placing the card in the state struct's discard array for the current player.

discardCard() method: The discardCard() method is used to discard a card from a player's hand (which is represented in a 2-D array) at the location handPos. discardCard() takes in a trashFlag parameter - if trashFlag is less than 1, then the card is added to the state->playedCards array which is discard pile; otherwise the card data is not saved in the discard pile and is removed from the game. The value of the card at handPos in the player's hand is set to -1. The method then removes the card from the hand. If the removed card was the last card in the state->hand array for the current player, or if it was the only card in the state->hand array, then the number of cards in the hand is decreased. Otherwise, the handPos index in the state->hand array for the current player is given the value of the last card in the hand array, and then the number of cards in the hand is decreased.

updateCoins() method: This method evaluates the player's hand to determine the total coin value in their hand. First, the state->coin value is reset to 0. Then each card in the player's hand is evaluated one by one in a for loop. If the card is a copper treasure card, state->coin increases by 1. state->coin increases by 2 if the card is a silver treasure card, and by 3 if the card is a gold treasure card. Any bonus points are added to state->coin after all the cards in the hand have been evaluated.


