/***************************************************************************
** Author: James Pool
** ONID: 932664412
** OSU Email: poolj@oregonstate.edu
** Date: 8 April 2016
**
** Program Filename: randomstring.c
** Description: This is the documentation file for Quiz 2: Random Testing. 
**				The functions inputChar() and inputString() were implemented
**				to produce random values.
***************************************************************************/

The inputChar() function is a very simple method that returns a single random
character from the set of all printable ASCII characters. This corrosponds
to the ASCII values 0x20 [space] (decimal 32) to 0x7E [~] (decimal 126). The
random ASCII value is generated using the following code:

					rand() % (127 - 32) + 32

The result is then casted to a character before being returned. While the cast might
not be required, I believe it is always a good idea to make it explicit. Based
on how the returned value from inputChar() is utilized, there is a 1 in 94 chance
for the state to transition to the next state.

The inputString() function is used to create a 5 character string with an null
terminator appended on the end. Random strings are generated by calling the prior
mentioned inputChar() function. Since the total possible combination of random string
(94^5 ~= 7,339,040,224) is extremly large, the probability of the required 'reset'
string being generated is extremly low (0.000000013%). Therefore, a short-circuiting
option was added that returns the 'reset' string with a reasonable probability of
(0.1%). This allows for testing random strings while still completing in a
reasonable amout of time for this exercise.

Analyzing the a sample execution of the program with gcov indicated that 97.56% of the
41 lines of code were executed (the non-executed line being the 'return 0' which is 
never reached due to the 'exit(200)' command call). Also, each of the 54 available branches
was executed with 90.74% taken at least once. The results from gcov indicate that 
there was excellent coverage.