Interestingly, I found essentially no problems with the unit functions, yet I encountered a number of new problems in card functions that I had even refactored before. 

In Smithy, I encountered the bugs that I had introduced. In theory, playing smithy allows the current player to receive exactly 3 cards from his own deck. Because I had left i uninitialized, the player could receive an unknown number of cards (in this case, i seemed to initialize to 1), changing the player’s hand count and deck count. Additionally, in the test with the second player, I was able to detect that playing Smithy took away another player’s hand (pushing it into the negative). 

In Remodel, I encountered a number of surprising bugs, especially considering that I purposely hadn’t introduced any. Instead of requiring that the new card cost a maximum of 2 greater than the current card, it required that the new card cost a minimum of 3 more than the current card, which completely reversed my expected test results. Additionally, even when it does actually play the Remodel card, it does not trash it, as required by the card, but merely puts it into the player’s discard pile, which almost defeats its purpose. 

In Embargo, I found the most surprising bug of all, which is that the effect of Embargo is nothing. I tested another player buying an “embargoed” card, but the next player never received any additional curses. 

In Adventurer, I encountered the bugs that I had introduced, as well as a few bugs I had not noticed. In all my test cases, I realized, the current hand was 1 more than I expected, the first card did not change, and the number of played cards after the turn was still 0, which made me realize that Adventurer did not properly discard the adventurer card after playing. Interestingly, this made it difficult to see my own bug later on, which sometimes discarded too many cards, since these canceled each other out. Finally, after testing the case in which neither the deck nor the discard pile has any treasure cards, I realized that Adventurer was stuck in an infinite loop. In the real game, the play simply ends once the player has revealed all cards and found no treasure cards. 
