Patrick Ho
coverage1.c
Assignment 3
Due April 24, 2016

General notes:  gcov files are saved after being ran. See folder ./results for the gcov files.

######## Coverage Test: unittest1 ########

	Unittest1 tests the handCard() function. The function was called 10 times and
	only covered roughly 0.5% of statements in dominion.c. Within that block of code, 
	however,the unit test covered 100% of the block. The following is a code snippet
	from the gcov file:

	function handCard called 10 returned 100% blocks executed 100%
        -:  315:int handCard(int handPos, struct gameState *state) {
       10:  316:  int currentPlayer = whoseTurn(state);
       10:  317:  return state->hand[currentPlayer][handPos];
        -:  318:}

	The following is the coverage results of dominion.c

	File 'dominion.c'
	Lines executed:0.47% of 643
	Branches executed:0.00% of 415
	Taken at least once:0.00% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

######## Coverage Test: unittest2 ########

	Unittest2 tests the updateCoins() function. The function was called twice
	by our unit test and executed with the following coverage statistics:

	File 'dominion.c'
	Lines executed:17.73% of 643
	Branches executed:15.90% of 415
	Taken at least once:13.25% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	updateCoins() is a well confined function and does not invoke functions that
	expands statement coverage. A majority of the statement and branch coverage
	presented in my results is drawn from testing the state of other players and
	checking the state of kingdom and victory cards.

######## Coverage Test: unittest3 ########

	Unittest3 tests the drawCard() function.  The function was called 15 times by
	our unit test and executed with the following coverage statistics:

	File 'dominion.c'
	Lines executed:20.06% of 643
	Branches executed:17.35% of 415
	Taken at least once:14.46% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	drawCards() is also a well confined function with only a call to the shuffle()
	function.  There is a branch within drawCard() that is never tested by our 
	unittest and that is when the deck is empty. In my unittest, the deck is never
	empty since the gameState is always instantiated as though it is the start of
	the game.  In our statistics, most of the statement and branch coverage is 
	covered when testing the state of other players.

######## Coverage Test: unittest4 ########

	Unittest4 tests the buyCard() function. The function was called 4 times by our
	unit test and executed with the following coverage statistics:

	File 'dominion.c'
	Lines executed:24.11% of 643
	Branches executed:26.99% of 415
	Taken at least once:17.11% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	buyCard() is another well confined function and does not invoke functions that
	expands statement coverage.  Other than the DEBUG statements, all statements
	are covered.  While about 24% of dominion.c statements are covered, most of
	these coverages come from checking supply piles and verifying that those piles
	have been reduced by the number of cards bought.

######## Coverage Test: cardtest1 ########

	cardtest1 tests the smithy card. The playSmithy() function was called only
	once and the execution of our unit test produced the following coverage 
	statistics:

	File 'dominion.c'
	Lines executed:27.22% of 643
	Branches executed:33.01% of 415
	Taken at least once:18.80% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	Statement coverage on the playSmithy() function is at 100%. A major portion of
	coverage generated by our cardtest is from intialization of the game and testing
	state changes to other players and checking for the appropriate amount of 
	kingdom and victory cards.

######## Coverage Test: cardtest2 ########

	cardtest2 tests the adventurer card. The playAdventuer() function was called 1
	time and the execution of our unit test produced the following coverage 
	statistics:

	File 'dominion.c'
	Lines executed:29.70% of 643
	Branches executed:34.94% of 415
	Taken at least once:20.48% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	Within playAdventuer(), a branch that invokes the shuffle() function is
	never executed because our gameState never sets the deck to be empty. This is a
	consistent coverage miss in my tests and in next iterations, I should consider
	testing while the game is further along, rather than at it's initial game state.
	Again, most of the statement and branch coverage of dominion.c is from initializing
	the game state, testing state changes to other players, and checking for the 
	appropriate amount of kingdom and victory cards.

######## Coverage Test: cardtest3 ########

	Cardtest3 tests the great hall card. The great hall card is a rather simplistic
	play. The case calls drawCard() and discardCard() functions and each statement
	within its case gets called once.  Our unit test produces the following coverage
	statistics:

	File 'dominion.c'
	Lines executed:30.33% of 643
	Branches executed:34.94% of 415
	Taken at least once:20.72% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	The great hall card is a simple action card. When played, it draws an extra card 
	and gains an extra action. A majority of the	coverage produced by our unittest 
	are from game initialization and testing game states.

######## Coverage Test: cardtest4 ########

	Cardtest4 tests the village card. The playVillage() function was called 2 times.
	Our unit test produces the following coverage statistics:

	File 'dominion.c'
	Lines executed:30.33% of 643
	Branches executed:34.94% of 415
	Taken at least once:20.72% of 415
	No calls
	dominion.c:creating 'dominion.c.gcov'

	The playVillage() function calls drawCard() and discardCard() functions, each called
	twice. 100% of the playVillage() block is executed.  dominion.c statement coverage is
	approximately at 30%.
