
	I should mention that I did a combination of black box and white box testing in these different tests, to try to gain some insights on the different strategies. For coverage I think it is much easier to use white box test, knowing the different branches certainly gives you an edge in covering them . However, I noticed I started to take things for granted when I reviewed the code toughly, and I think there is certainly some value in black box testing however inefficient it might be.  
	The smithy_function proved to be very easy to get full branch coverage in testing due to no branching.  I also choose to do the getCost function, I thought as a jr team member at a future job I might have to create a unit test for something very straightforward like that. Even with how easy it was I didn’t reach 100 coverage because I neglected the case where the card didn’t match the enum. 
	While my coverage on the adventurer function was ok, I still wasn’t able to reach all paths being taken, but at least all branches were ran. 
	Of coarse the cardEffect function had very low coverage and is probably one of the most important functions in the game. It is easy to see the 13.29 branch coverage is from the 4 only cards I tested, since 4 out of the 29 cards plus one function Is 13%. To increase coverage on this vital function one would have to prepare a test for every card unique to that card. 
	I think the largest insight of this assignment was how each test needs to be unique enough to hit every branch, but at the same time very similar form than many of the other functions tests. 
	Lastly I did manage to get good coverage on the gainCard function. This is because that code is self-documented and well written. I think testing code that is both documented and well written is much easier to accomplish than code that doesn’t have those features. I really feel like testing is a 2 way street in that regard. Well documented code is easier to test and will end up being even more robust as a result of the documentation and intuition it provides. 
	Finally in summary, I found my first attempt at code coverage via testing to be lacking. Searching out a test case for each and every conditional would certainly help that coverage score. 

