/*
James Guerra quiz 2 4/24/16

For this quiz I created a pair of functions in the testme.c 
file for generating a random character and for making up strings 
using that first function.  In order to meet the requirements of the 
exit statement these strings had a 6th char containing the value /0.  
While generating the exit statement is unlikely to occur quickly it is possible
using the functions as written.  To improve the run time of the program you could
decrease the number of possibilities generated by inputChar()




*/